# Open-WebUI Hoster Configuration

# Open-WebUI Container Settings
openwebui:
  image: ghcr.io/open-webui/open-webui:latest
  port: 3000
  # API integrations
  api_keys:
    openrouter: ""  # Your OpenRouter API key

# Ollama Container Settings
ollama:
  image: ollama/ollama
  download_models: [llama3.2 deepseek-r1]  # Add model names to download on startup, e.g. ["llama3", "mistral"]

# Ngrok Tunnel Settings
ngrok:
  region: us  # Options: us, eu, ap, au, sa, jp, in
  update_interval: 300  # How often to refresh URL in logs (seconds)