# Open-WebUI Hoster Configuration

# Open-WebUI Container Settings
openwebui:
  image: ghcr.io/open-webui/open-webui:latest
  port: 3000
  # API integrations
  api_keys:
    openrouter: "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"  # Your OpenRouter API key

# Ollama Container Settings
ollama:
  image: ollama/ollama
  download_models: ["llama3.2:1b", "llama3.2:3b", "deepseek-r1", "deepseek-r1:1.5b"]

# Ngrok Tunnel Settings
ngrok:
  region: us  # Options: us, eu, ap, au, sa, jp, in
  update_interval: 300  # How often to refresh URL in logs (seconds)
