name: Host Open-WebUI

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  host-openwebui:
    runs-on: ubuntu-latest
    timeout-minutes: 55  # Auto-restart before GitHub's 6-hour limit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load configuration
        id: config
        run: |
          sudo apt-get install -y yq jq
          echo "OPENWEBUI_IMAGE=$(yq '.openwebui.image' config.yml)" >> $GITHUB_ENV
          echo "OPENWEBUI_PORT=$(yq '.openwebui.port' config.yml)" >> $GITHUB_ENV
          echo "OLLAMA_IMAGE=$(yq '.ollama.image' config.yml)" >> $GITHUB_ENV
          echo "MODELS_FILE=$(yq '.ollama.models_file' config.yml)" >> $GITHUB_ENV
          echo "DOWNLOAD_MODELS=$(jq -r '.models | join(" ")' $(yq -r '.ollama.models_file' config.yml))" >> $GITHUB_ENV
          echo "NGROK_REGION=$(yq '.ngrok.region' config.yml)" >> $GITHUB_ENV
          echo "UPDATE_INTERVAL=$(yq '.ngrok.update_interval' config.yml)" >> $GITHUB_ENV
          echo "OPENROUTER_API_KEY=$(yq '.openwebui.api_keys.openrouter' config.yml)" >> $GITHUB_ENV

      - name: Create Docker network
        run: |
          if ! docker network inspect openwebui-network > /dev/null 2>&1; then
            docker network create openwebui-network
          else
            echo "Docker network 'openwebui-network' already exists."
          fi

      - name: Start Ollama container
        run: |
          docker run -d --name ollama \
            --network openwebui-network \
            -v ollama:/root/.ollama ${{ env.OLLAMA_IMAGE }}
          
          # Wait for Ollama to initialize
          echo "Waiting for Ollama to initialize..."
          sleep 10
          
          # Download configured models if any
          if [ ! -z "$DOWNLOAD_MODELS" ]; then
            for model in $DOWNLOAD_MODELS; do
              echo "Downloading model: $model"
              docker exec ollama ollama pull $model
            done
          fi
        env:
          DOWNLOAD_MODELS: ${{ env.DOWNLOAD_MODELS }}

      - name: Start Open-WebUI container
        run: |
          docker run -d --name open-webui \
            --network openwebui-network \
            -p ${{ env.OPENWEBUI_PORT }}:${{ env.OPENWEBUI_PORT }} \
            -v open-webui:/app/backend/data \
            -e OLLAMA_API_BASE_URL=http://ollama:11434/api \
            -e OPENROUTER_API_KEY=${{ env.OPENROUTER_API_KEY }} \
            ${{ env.OPENWEBUI_IMAGE }}
          
          # Wait for Open-WebUI to initialize
          echo "Waiting for Open-WebUI to start..."
          sleep 15
          
          # Check if Open-WebUI is running properly
          if ! curl -s http://localhost:${{ env.OPENWEBUI_PORT }} > /dev/null; then
            echo "ERROR: Open-WebUI is not responding. Container logs:"
            docker logs open-webui
            exit 1
          else
            echo "Open-WebUI is running successfully!"
          fi

      - name: Start ngrok tunnel and get URL
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/ngrok.gpg
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok jq
          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          ngrok http ${{ env.OPENWEBUI_PORT }} --region=${{ env.NGROK_REGION }} --log=stdout > ngrok.log &
          
          # Wait for ngrok to start
          echo "Starting ngrok tunnel..."
          sleep 10
          
          # Function to display the URL
          display_url() {
            url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            echo "============================================="
            echo "🌐 Access URL: $url"
            echo "============================================="
          }
          
          # Display URL initially
          display_url
          
          # Keep the workflow running and update URL every configured interval
          while true; do
            sleep ${{ env.UPDATE_INTERVAL }}
            display_url
          done
