      - name: Start Ollama container
        run: |
          docker run -d --name ollama -v ollama:/root/.ollama ${{ env.OLLAMA_IMAGE }}
          
          # Wait for Ollama to initialize
          echo "Waiting for Ollama to initialize..."
          sleep 10
          
          # Download configured models if any
          if [ ! -z "$DOWNLOAD_MODELS" ]; then
            for model in $DOWNLOAD_MODELS; do
              echo "Downloading model: $model"
              docker exec ollama ollama pull $model
            done
          fi
        env:
          DOWNLOAD_MODELS: ${{ env.DOWNLOAD_MODELS }}
